# Generated by Django 4.2.6 on 2024-01-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='slocation',
            new_name='Slocation',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='sname',
            new_name='Sname',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='sprincipal',
            new_name='Sprincipal',
        ),
    ]
