# Generated by Django 4.2.6 on 2024-01-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_slocation_school_slocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(default='indian@gmial.com', max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='reenteremail',
            field=models.EmailField(default='indian@gmail.com', max_length=254),
        ),
    ]
